apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gopass
spec:
  provider:
    webhook:
      url: "http://localhost:3000/eso?name={{ .remoteRef.key }}"
      result:
        jsonPath: "$.value"
