apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gopass
spec:
  provider:
    webhook:
      url: "http://external-secrets-gopass-webhook.external-secrets.svc:80/api/get?name={{ .remoteRef.key }}"
      result:
        jsonPath: "$.value"
      headers:
        Content-Type: application/json
        Authorization: Basic {{ print .auth.API_AUTH_USER ":" .auth.API_AUTH_PASS | b64enc }}
      secrets:
      - name: auth
        secretRef:
          name: gopass-webhook-credentials
          namespace: external-secrets
