apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gopass
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: test_json
