---
apiVersion: v1
kind: Secret
metadata:
  name: gopass-webhook
  namespace: external-secrets
stringData:
  GIT_WEBHOOK_SECRET: "<random string>"
  GPG_SECRET: |-
    <output of gpg --export-secret-key | base64>
  REPO_URL: "https://<token name>:<token value>@<repo>"
